name: Test Build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: '18.17.0'
      
     - name: Compile
       env:
         CI: false
       run: |
         npm install;
         npm run build;
         
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}       
         publish_dir: ./build
         cname: qa.taoist.dev

